In [1]:
import tensorflow as tf

In [2]:
mnist=tf.keras.datasets.mnist

In [3]:
(x_train,y_train), (x_test,y_test)=mnist.load_data()

11493376/11490434 [==============================] - 5s 0us/step


In [5]:
model=tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10),
    
])

In [8]:
predictions=model(x_train[:1]).numpy()

In [9]:
predictions

array([[-149.196   ,  -63.5568  ,   68.50217 ,  -88.54707 , -131.5173  ,
          62.720234,  -76.61562 , -106.18636 , -170.34036 ,   15.187218]],
      dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.0000000e+00, 0.0000000e+00, 9.9692672e-01, 0.0000000e+00,
        0.0000000e+00, 3.0732772e-03, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 6.9867478e-24]], dtype=float32)

In [17]:
loss_function=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [18]:
loss

In [19]:
loss_function(y_train[:1],predictions).numpy()

5.785011

In [22]:
model.compile(optimizer='adam',
              loss=loss_function,
              metrics=['accuracy'])

In [23]:
model.fit(x_train,y_train,epochs=25)

Epoch 1/25
1875/1875 [==============================] - 5s 2ms/step - loss: 8.2166 - accuracy: 0.7003
Epoch 2/25
1875/1875 [==============================] - 4s 2ms/step - loss: 0.5884 - accuracy: 0.8423
Epoch 3/25
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4648 - accuracy: 0.8749
Epoch 4/25
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4236 - accuracy: 0.8900
Epoch 5/25
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3820 - accuracy: 0.8991
Epoch 6/25
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3739 - accuracy: 0.9020
Epoch 7/25
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3453 - accuracy: 0.9100
Epoch 8/25
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3400 - accuracy: 0.9127
Epoch 9/25
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3365 - accuracy: 0.9127
Epoch 10/25
1875/1875 [==============================] - 4s 2ms/step - loss: 0.322

In [24]:
model.evaluate(x_test,y_test,verbose=3)

[0.33842551708221436, 0.9416000247001648]

In [28]:
probability_model=tf.keras.Sequential([model,
                                       tf.keras.layers.Softmax()])

In [29]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.0000000e+00, 0.0000000e+00, 2.2763594e-32, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 4.1110914e-07, 9.9999964e-01, 1.3375607e-22,
        5.0338260e-37, 0.0000000e+00, 3.6444368e-36, 8.8759323e-19,
        1.7690260e-25, 0.0000000e+00],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        1.2937628e-19, 0.0000000e+00, 8.7563952e-23, 1.2492763e-23,
        1.7714222e-27, 0.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 1.0655421e-16, 3.5935733e-17,
        1.3215678e-25, 1.6363464e-15, 2.6391138e-16, 9.1622977e-12,
        1.2378677e-15, 7.5558329e-15],
       [1.7852629e-25, 2.4943722e-20, 2.9100705e-13, 1.2267396e-17,
        1.0000000e+00, 1.8958572e-08, 4.0939511e-17, 1.7040605e-12,
        5.4956468e-23, 1.2137397e-08]], dtype=float32)>